version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: pg_query
    versions:
    - 1.3.0
    - 2.0.1
    - 2.0.2
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: rails
    versions:
    - 6.0.3.4
    - 6.0.3.5
  - dependency-name: bullet
    versions:
    - 6.1.3
  - dependency-name: rack-mini-profiler
    versions:
    - 2.3.0
  - dependency-name: brakeman
    versions:
    - 4.10.1
