AllCops:
  Exclude:
    - 'Guardfile'
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 17

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'