AllCops:
  Exclude:
    - 'Guardfile'
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/models/application_record.rb'
    - 'app/mailers/application_mailer.rb'