dist: trusty
language: ruby
rvm:
 - 2.3
cache: 
  - bundler
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432"
env:
  global:
    - RAILS_ENV=test
before_script:
  - bundle exec rake db:create db:migrate --trace
script: 
  - bundle exec rspec  