dist: trusty
language: ruby
rvm:
 - 2.3
cache: 
  - bundler
addons:
  postgresql: 
    - "9.6"
env:
  global:
    - RAILS_ENV=test
before_script:
  - bundle exec rake db:create db:migrate --trace
script: 
  - bundle exec rspec  