dist: trusty
language: ruby
rvm:
  - 2.5.1
cache:
  - bundler
services:
  postgres:
    image: postgres:10.0
    ports:
      - '5432'
env:
  global:
    - RAILS_ENV=test
    - PRONTO_PULL_REQUEST_ID=$TRAVIS_PULL_REQUEST
before_script:
  - bundle exec rake db:create db:migrate --trace
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" == false ]; then echo "TRAVIS_PULL_REQUEST is unset, skipping Pronto"; else bundle exec pronto run -f github_pr -c origin/develop; fi'
  - bundle exec rspec
  